global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ingest'
    static_configs:
      - targets: ['ingest:8080']
    metrics_path: '/metrics'

  - job_name: 'api'
    static_configs:
      - targets: ['api:8081']
    metrics_path: '/metrics'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
